/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.models.DiagnosticoDAO;
import com.mycompany.models.Enfermedad;
import com.mycompany.models.EnfermedadDAO;
import com.mycompany.models.Paciente;
import com.mycompany.models.PacienteDAO;
import com.mycompany.models.Sintoma;
import com.mycompany.models.SintomaDAO;
import com.mycompany.prolog.PrologQueryExecutor;
import java.awt.Component;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel
 */
public class DiagnosticoPaciente extends javax.swing.JDialog {

    private List<Enfermedad> pE;
    private List<Sintoma> ss;
    private Paciente p;

    public DiagnosticoPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBounds(0, 0, 1350, 650);
        panelSintomas.setLayout(new BoxLayout(panelSintomas, BoxLayout.Y_AXIS));
        generarSintomasCheckBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSintomas = new javax.swing.JPanel();
        txtNombrePaciente = new javax.swing.JTextField();
        txtEdadPaciente = new javax.swing.JTextField();
        txtIdPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSintomasSeleccionados = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPosiblesEnfermedades = new javax.swing.JTextArea();
        btnCrearDiagnostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 224, 221));

        javax.swing.GroupLayout panelSintomasLayout = new javax.swing.GroupLayout(panelSintomas);
        panelSintomas.setLayout(panelSintomasLayout);
        panelSintomasLayout.setHorizontalGroup(
            panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        panelSintomasLayout.setVerticalGroup(
            panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre Paciente");

        jLabel2.setText("Edad del paciente");

        jLabel3.setText("Identificacion paciente");

        btnGenerar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnGenerar.setText("GENERAR");
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarMouseExited(evt);
            }
        });

        jLabel4.setText("Sinomas Seleccionados:");

        txtSintomasSeleccionados.setColumns(20);
        txtSintomasSeleccionados.setRows(5);
        jScrollPane1.setViewportView(txtSintomasSeleccionados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Posibles Enfermedades");

        txtPosiblesEnfermedades.setColumns(20);
        txtPosiblesEnfermedades.setRows(5);
        jScrollPane2.setViewportView(txtPosiblesEnfermedades);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        btnCrearDiagnostico.setFont(new java.awt.Font("Tempus Sans ITC", 0, 15)); // NOI18N
        btnCrearDiagnostico.setText("CREAR DIAGNOSTICO");
        btnCrearDiagnostico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearDiagnosticoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearDiagnosticoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearDiagnosticoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnCrearDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombrePaciente)
                            .addComponent(txtEdadPaciente))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(63, 63, 63))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseEntered
        this.btnGenerar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnGenerarMouseEntered

    private void btnGenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseExited
        this.btnGenerar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnGenerarMouseExited

    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked
        this.txtSintomasSeleccionados.setText(null);
        this.txtPosiblesEnfermedades.setText("Enfermedad|Categoria|Recomendaciones"+"\n"+"\n");
        if (this.txtNombrePaciente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se puede generar el diagnostico sin el nombre del paciente");
            return;
        }
        String n = this.txtNombrePaciente.getText();

        try {
            PacienteDAO pdao = new PacienteDAO();
            this.p = pdao.buscarPaciente(n);

            this.txtNombrePaciente.setText(p.getNombre());
            this.txtEdadPaciente.setText(String.valueOf(p.getEdad()));
            this.txtIdPaciente.setText(String.valueOf(p.getId()));

        } catch (SQLException ex) {
            System.getLogger(PacienteDAO.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        this.ss = obtenerSeleccionados();
        for (Sintoma s : ss) {
            this.txtSintomasSeleccionados.append(s.getId() + ". " + s.getNombre() + "\n");
        }

        this.pE = pEnfermedades(ss);
        for(Enfermedad f: pE){
            Enfermedad en = PrologQueryExecutor.getEnfermedad("enfermedad("+f.getNombre()+",sintomas(Sin),categoria(Cat),recomendaciones(Rec))");
            txtPosiblesEnfermedades.append(f.getNombre()+"  |  "+en.getCategoria()+"  |  "+en.getRecomendaciones()+"\n"+"\n");
        }

    }//GEN-LAST:event_btnGenerarMouseClicked

    private void btnCrearDiagnosticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDiagnosticoMouseEntered
        this.btnCrearDiagnostico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCrearDiagnosticoMouseEntered

    private void btnCrearDiagnosticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDiagnosticoMouseExited
        this.btnCrearDiagnostico.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnCrearDiagnosticoMouseExited

    private void btnCrearDiagnosticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearDiagnosticoMouseClicked
        if (txtIdPaciente.getText().isEmpty() || txtIdPaciente.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "no se puede guardar el diagnostico sin seleccionar sintomas o un paciente valido");
        }
        EnfermedadDAO edao = new EnfermedadDAO();
        List<Sintoma> sd = this.ss;
        Enfermedad e = enfermedadMasProbable(this.pE);
        Enfermedad ed = null;
        try {
            ed = edao.obtenerEnfermedad(e.getNombre());
        } catch (SQLException ex) {
            System.getLogger(EnfermedadDAO.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        int idP = Integer.parseInt(txtIdPaciente.getText());
        int idE = ed.getId();

        try {
            DiagnosticoDAO ddao = new DiagnosticoDAO();
            if (ddao.agregarDiagnostico(idP, idE, sd)) {
                JOptionPane.showMessageDialog(this, "Diagnostico agregado correctamente a la base de datos");
                this.dispose();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "error al intentar insertar el paciente en la base de datos" + ex.getMessage());
        }
    }//GEN-LAST:event_btnCrearDiagnosticoMouseClicked

    private void generarSintomasCheckBox() {
        SintomaDAO sdao = new SintomaDAO();
        try {
            List<Sintoma> sintomas = sdao.obtenerSintomas();
            for (Sintoma s : sintomas) {
                String txt = s.getId() + ". " + s.getNombre();
                JCheckBox cb = new JCheckBox(txt);
                cb.putClientProperty("data", s);
                panelSintomas.add(cb);
            }
        } catch (SQLException ex) {
            System.getLogger(SintomaDAO.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private List<Sintoma> obtenerSeleccionados() {
        List<Sintoma> selected = new ArrayList<>();
        for (Component comp : panelSintomas.getComponents()) {
            if (comp instanceof JCheckBox cb) {
                if (cb.isSelected()) {
                    Sintoma s = (Sintoma) cb.getClientProperty("data");
                    selected.add(s);
                }
            }
        }
        return selected;
    }

    private List<Enfermedad> pEnfermedades(List<Sintoma> s) {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        for (int i = 0; i < s.size(); i++) {
            Sintoma si = s.get(i);
            sb.append(si.getNombre());
            if (i < s.size() - 1) {
                sb.append(",");
            }
        }
        sb.append("]");

        List<Enfermedad> Eexacta = PrologQueryExecutor.getEnfermedades("coincide_sintomas(" + sb.toString() + ",Nom)");

        if (!Eexacta.isEmpty()) {
            return Eexacta;
        }

        List<Enfermedad> posiblesEnf = PrologQueryExecutor.getEnfermedades("diagnostico(" + sb.toString() + ",Nom)");

        return posiblesEnf;
    }

    private Enfermedad enfermedadMasProbable(List<Enfermedad> lista) {

        Map<String, Integer> contador = new HashMap<>();

        for (Enfermedad e : lista) {
            contador.put(e.getNombre(), contador.getOrDefault(e.getNombre(), 0) + 1);
        }

        String mejor = null;
        int max = 0;

        for (Map.Entry<String, Integer> entry : contador.entrySet()) {
            if (entry.getValue() > max) {
                mejor = entry.getKey();
                max = entry.getValue();
            }
        }

        // devolver el objeto Enfermedad original
        for (Enfermedad e : lista) {
            if (e.getNombre().equals(mejor)) {
                return e;
            }
        }

        return null; // no debería pasar
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearDiagnostico;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelSintomas;
    private javax.swing.JTextField txtEdadPaciente;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextArea txtPosiblesEnfermedades;
    private javax.swing.JTextArea txtSintomasSeleccionados;
    // End of variables declaration//GEN-END:variables
}
